version: '3.9'
services:
  server:
    build:
      context: server
    environment:
      GIN_MODE: release
    ports:
      - '8000:8000'
    volumes:
      - ./server:/server
  docs:
    build:
      context: server/docs
    ports:
      - '8080:8080'
    volumes:
      - ./server/docs:/docs