version: '3.9'
services:
  server:
    build:
      context: server
    environment:
      GIN_MODE: release
    ports:
      - '8000:8000'
    volumes:
      - ./server:/server
  server_docs:
    build:
      context: server/docs
    ports:
      - '8080:8080'
  app_docs:
    build:
      context: app
    ports:
      - '8081:8081'
    volumes:
      - ./app/doc/api:/docs/app
    command: >
      sh -c "pub global activate dartdoc
      && pub global activate dhttpd
      && dartdoc
      && dhttpd --path doc/api --port 8081"
