version: '3.9'
services:
  server:
    build:
      context: server
    environment:
      GIN_MODE: release
    ports:
      - '8000:8000'
    volumes:
      - ./server:/server
  server_docs:
    build:
      context: server/docs
    ports:
      - '8080:8080'
<<<<<<< HEAD
 # app_docs:
 #   build:
 #     context: app
 #   ports:
 #     - '8081:8081'
 #   volumes:
 #     - ./app:/app
=======
  # app_docs:
  #   build:
  #     context: app
  #   ports:
  #     - '8081:8081'
  #   volumes:
  #     - ./app:/app
>>>>>>> 638efce (.md files clarifications, docker configuration cleanup)
  swagger-ui:
    image: docker.io/swaggerapi/swagger-ui
    environment:
      - URL=http://localhost:8090/swagger.json
      - SWAGGER_JSON=/swagger.json
    ports:
      - "8090:8080"
    volumes:
<<<<<<< HEAD
      - ./docs/swagger-api-docs/swagger-api-docs.yaml:/swagger.json

=======
      - ./docs/swagger-api-docs/swagger-api-docs.yaml:/swagger.json
>>>>>>> 638efce (.md files clarifications, docker configuration cleanup)
