name: Go

on: [pull_request]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
            
    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v2.5.2
      with:
        working-directory: ./server
        skip-go-installation: true

    - name: Build
      working-directory: ./server
      run: make

    - name: Test
      working-directory: ./server
      run: make test
